todo/urls.py
from django.conf.urls.defaults import *
from django.views.generic.simple import direct_to_template
from django.contrib.auth import views as auth_views

urlpatterns = patterns('',
    url(r'^mine/$', 'todo.views.view_list',{'list_slug':'mine'},name="todo-mine"),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/delete$', 'todo.views.del_list',name="todo-del_list"),
    url(r'^task/(?P<task_id>\d{1,6})$', 'todo.views.view_task', name='todo-task_detail'),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)$', 'todo.views.view_list', name='todo-incomplete_tasks'),
    url(r'^(?P<list_id>\d{1,4})/(?P<list_slug>[\w-]+)/completed$', 'todo.views.view_list', {'view_completed':1},name='todo-completed_tasks'),    
    url(r'^$', 'todo.views.list_lists',name="todo-lists"),
    url(r'^not_available/$', direct_to_template, dict(template='todo/no_available.html'), name="todo-not-available"),
    
    # View reorder_tasks is only called by JQuery for drag/drop task ordering
    url(r'^reorder_tasks/$', 'todo.views.reorder_tasks',name="todo-reorder_tasks"),
)

todo/models.py
from django.db import models
from django.forms.models import ModelForm
from django import forms
from django.contrib import admin
from django.contrib.auth.models import User
from muaccounts  import models as muamodels

import string, datetime

class ListManager(models.Manager):
    """
    Retrieves all incomplete tasks for a given list.
    """
    def get_query_set(self):
        return super(ListManager, self).get_query_set().filter(completed=0)

class List(models.Model):
    name = models.CharField(max_length=60)
    slug = models.SlugField(max_length=60,editable=False)

    #group = models.ForeignKey(Group)
    account = models.ForeignKey(muamodels.MUAccount)

    def save(self):
        if not self.id:
            # Replace spaces in slug with hyphens, and lowercase.
            self.slug = (self.name).lower().replace(' ','-')

            # Regex to remove non-alphanumeric chars, using re (regular experession module)
            # If we end up with double hyphens, remove those too.
            import re
            self.slug = re.sub(r"[^A-Za-z0-9\-]", "", self.slug).replace('--','-')

            super(List, self).save()

    def __unicode__(self):
        return self.name

    # Custom manager lets us do things like Item.completed_tasks.all()
    objects = models.Manager()
    incomplete_tasks = ListManager()

    class Meta:
        ordering = ["name"]
        verbose_name_plural = "Lists"

        # Prevents (at the database level) creation of two lists with the same name in the same group
        unique_together = ("account", "slug")





class Item(models.Model):
    title = models.CharField(max_length=140)
    list = models.ForeignKey(List)
    created_date = models.DateField()
    due_date = models.DateField(blank=True,null=True,)
    completed = models.BooleanField()
    completed_date = models.DateField(blank=True,null=True)
    created_by = models.ForeignKey(User, related_name='created_by')
    assigned_to = models.ForeignKey(User, related_name='todo_assigned_to')
    note = models.TextField(blank=True)
    priority = models.PositiveIntegerField(max_length=3)

    # Model method: Has due date for an instance of this object passed?
    def overdue_status(self):
        "Returns whether the item's due date has passed or not."
        if datetime.date.today() > self.due_date :
            return 1

    def __unicode__(self):
        return self.title

    # Auto-set the item creation / completed date
    def save(self):
        # Set datetime on initial item save
        if not self.id:
            self.created_date = datetime.datetime.now()

        # If Item is being marked complete, set the completed_date
        if self.completed :
            self.completed_date = datetime.datetime.now()
        super(Item, self).save()


    class Meta:
        ordering = ["priority"]


class Comment(models.Model):
    """
    Not using Django's built-in comments becase we want to be able to save
    a comment and change task details at the same time. Rolling our own since it's easy.
    """
    author = models.ForeignKey(User)
    task = models.ForeignKey(Item)
    date = models.DateTimeField(default=datetime.datetime.now)
    body = models.TextField(blank=True)

    def __unicode__(self):
        return '%s - %s' % (
                self.author,
                self.date,
                )

todo/forms.py
from django.db import models
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User,Group
from todo.models import Item, List
import datetime
from muaccounts  import models as muamodels


class AddListForm(ModelForm):
    # slug = models.SlugField(widget=HiddenInput)
    # slug = forms.CharField(widget=forms.HiddenInput)

    # The picklist showing allowable groups to which a new list can be added
    # determines which groups the user belongs to. This queries the form object
    # to derive that list.
    def __init__(self, user, *args, **kwargs):
        super(AddListForm, self).__init__(*args, **kwargs)
        #self.fields['group'].queryset = Group.objects.filter(user=user)

    class Meta:
        model = List
        exclude = ('account')



class AddItemForm(ModelForm):
    due_date = forms.DateField(
                    required=False,
                    widget=forms.DateTimeInput(attrs={'class':'due_date_picker'})
                    )

    title = forms.CharField(
                    widget=forms.widgets.TextInput(attrs={'size':35})
                    )

    # The picklist showing the users to which a new task can be assigned
    # must find other members of the groups the current list belongs to.
    def __init__(self, task_list, muaccount, *args, **kwargs):
        super(AddItemForm, self).__init__(*args, **kwargs)
        # print dir(self.fields['list'])
        # print self.fields['list'].initial

        membs = muaccount.members.all()
        own = User.objects.filter(id=muaccount.owner.id) # i need to do this in order to combine both
        membs = membs | own

        self.fields['assigned_to'].queryset = membs

    class Meta:
        model = Item



class EditItemForm(ModelForm):

    def __init__(self, muaccount, *args, **kwargs):
        super(EditItemForm, self).__init__(*args, **kwargs)

        membs = muaccount.members.all()
        own = User.objects.filter(id=muaccount.owner.id) # i need to do this in order to combine both
        membs = membs | own

        self.fields['assigned_to'].queryset = membs



    class Meta:
        model = Item

        exclude = ('list','created_by')

todo/templates/todo/base.html
{% extends "main.html" %}

{% block head %}
<!-- CSS and JavaScript for django-todo -->
<link rel="stylesheet" type="text/css" href="/media/todo/css/styles.css" />

<script src="/media/jquery/js/ui.datepicker.js" type="text/javascript"></script>
<script src="/media/todo/js/jquery.tablednd_0_5.js" type="text/javascript"></script>
<link type="text/css" href="/media/js/jquery-ui-1.7.1.custom.css" rel="Stylesheet" />


<script type="text/javascript" charset="utf-8">
    // thedate.x comes from the edit_task view. If this is a new entry,
    // thedate won't be present and datepicker will fall back on the default (today).
    $(document).ready(function(){
        $('#id_due_date').datepicker({defaultDate: new Date({{thedate.year}}, {{thedate.month}} - 1, {{thedate.day}}),});
     });
</script>

{% endblock %}

todo/templates/todo/del_list.html
{% extends "base.html" %}

{% block title %}{{ list_title }} to-do items{% endblock %}

{% block body %}

{# Only admins can delete lists. #}
{% ifequal can_del 1 %}


    {% if list_killed %}

       <p> {{ list.name }} is gone.</p>

        <a href="{% url todo-lists %}">Return to lists</a>

    {% else %}

        <h1>Delete entire list: {{ list.name }} ?</h1>

        <p>Category tally:</p>

         <ul>
            <li>Incomplete: {{ item_count_undone }} </li>
            <li>Complete: {{ item_count_done }} </li>
            <li><strong>Total: {{ item_count_total }}</strong> </li>
         </ul>

        <p> ... all of which will be irretrievably <strong>blown away</strong>. Are you sure you want to do that?</p>

        <form action="" method="post" accept-charset="utf-8">

            <input type="hidden" name="list" value="{{ list.id }}" id="some_name">
         <p><input type="submit" name="delete-confirm" value="Do it! &rarr;" class="todo-button"> </p>
        </form>


        <a href="{% url todo-incomplete_tasks list.id list_slug %}">Return to list: {{ list.name }}</a>

    {% endif %}


{% else %}

    <p>Sorry, you don't have permission to delete lists. Please contact your group administrator.</p>

{% endifequal %}







{% endblock %}

todo/templates/todo/list_lists.html
{% extends "todo/base.html" %}

{% block title %}{{ list_title }} Todo Lists{% endblock %}

{% block body %}


    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

   <h1>To-do Lists</h1>

   <p>{{ item_count }} items in {{ list_count }} lists</p>

   	<ul class="mainlist">
   		{% for list in list_list %}
   	        <li><a class="todo" href="{% url todo-incomplete_tasks list.id list.slug %}">{{ list.name }} - {{ list.group }}</a> ({{ list.incomplete_tasks.count }}/{{ list.item_set.count }})</li>
   	    {% endfor %}
   	</ul>

    <div class="todo-break">
    &nbsp;
    </div>

    <h2>Add a list:</h2>

	<form action="." method="POST">
	<table>{{ form }}</table>
	<p><input type="submit" value="Submit" class="todo-button"></p>
	</form>

{% endblock %}

todo/templates/todo/not_available.html
{% extends "todo/base.html" %}

{% block title %}Not available{% endblock %}

{% block head %}{% endblock %}

{% block body %}
<h1>Tasks not available</h1>
<p>You don't have Tasks activated for you plan.</p>
{% endblock %}

todo/templates/todo/view_list.html
{% extends "todo/base.html" %}

{% block title %}Todo List: {{ list.name }}{% endblock %}

{% block body %}

<script type="text/javascript">

function order_tasks(data) {
    // The JQuery plugin tableDnD provides a serialize() function which provides the re-ordered
    // data in a list. We pass that list as an object called "data" to a Django view
    // to save the re-ordered data into the database.

    $.post("{% url todo-reorder_tasks %}", data, "json");
    return False;
};

$(document).ready(function() {
    // Initialise the task table for drag/drop re-ordering
    $("#tasktable").tableDnD();

    $('#tasktable').tableDnD({
        onDrop: function(table, row) {
            order_tasks($.tableDnD.serialize());
        }
    });

    // Initially hide the Add Task form
    $('#AddTask').hide();

    // toggle slide to show the Add Task form when link clicked
    $('#slideToggle').click(function(){
        $(this).siblings('#AddTask').slideToggle();
    });
});

</script>


    {% ifequal list_slug "mine" %}
        <h1>Tasks assigned to {{ request.user }}</h1>
    {% else %}
    {% ifequal auth_ok 1 %}
       <h1>Tasks filed under "{{ list.name }}"</h1>
    {% endifequal %}
    {% endifequal %}


	<a href="{% url scratchpad-scratchpad_view list.scratchpad_set.all.0.id %}">Back to Scratchpad</a>

   {% if messages %}
   <ul class="messages">
       {% for message in messages %}
       <li>{{ message }}</li>
       {% endfor %}
   </ul>
   {% endif %}


   {% ifequal auth_ok 1 %}
   <form action="" method="POST">

   {# Only show task adder if viewing a proper list #}
   {% ifnotequal list_slug "mine" %}
   <h2 style="margin-bottom:0px;" id="slideToggle" >&rarr; Click to add task &larr;</h2>

   <div id="AddTask">
	    <table class="nocolor" border="0" cellspacing="5" cellpadding="5">
	       <tr>
	           <td>{{ form.title.errors }}</td>
	           <td>{{ form.due_date.errors }}</td>
	       </tr>
	       <tr>
	           <td><label for="id_title">Task:</label> {{ form.title }}</td>
	           <td><label for="id_due_date">Due date:</label> {{ form.due_date }}</td>
	           <td><label for="id_assigned">Assign to:</label> {{ form.assigned_to }}</td>
	           <td><label for="id_notify">Notify*:</label> <input type="checkbox" checked="checked" name="notify" value="1" id="notify"></td>
 	       </tr>
	       <tr>
	           <td colspan="5"><label for="id_note">Note:</label> {{ form.note }}
	               <p class="minor">*Email notifications will only be sent if task is assigned to someone besides yourself.</p>
	           </td>
 	       </tr>
	    </table>

        <input type="hidden" name="priority" value="999" id="id_priority">
        <input type="hidden" name="created_by" value="{{ request.user.id }}" id="id_created_by">
        <input type="hidden" name="list" value="{{ listid }}" id="id_list">
        <input type="hidden" name="created_date" value="{{ created_date }}" id="id_created_date">

	    <p><input type="submit" name="add_task" value="Add task" class="todo-button"></p>
    </div>

        {% endifnotequal %}


    {% ifequal view_completed 0  %}

	<h3>Incomplete tasks :: Drag rows to set priorities</h3>

	<table border="0" id="tasktable">
        <tr>
            <th>Done</th>
            <th>Task</th>
            <th>Created</th>
            <th>Due on</th>
            <th>Owner</th>
            <th>Assigned</th>
            <th>Note</th>
            <th>Comm</th>

            {% ifequal list_slug "mine" %}
            <th>List</th>
             {% endifequal %}

            <th>Del</th>
        </tr>
		{% for task in task_list %}
	        <tr class="{% cycle 'row1' 'row2' %}" id="{{ task.id }}">
	            <td><input type="checkbox" name="mark_done" value="{{ task.id }}" id="mark_done_{{ task.id }}">   </td>
	            <td><a href="{% url todo-task_detail task.id %}">{{ task.title|truncatewords:20 }}</a></td>
	            <td>{{ task.created_date|date:"m/d/Y" }}</td>
	            <td>
	            {% if task.overdue_status %}<span class="overdue">{% endif %}
	                {{ task.due_date|date:"m/d/Y" }}
	            {% if task.overdue_status %}</span>{% endif %}
	            </td>
	            <td>{{ task.created_by }}</td>
	            <td>{{ task.assigned_to }}</td>
	            <td style="text-align:center;">{% if task.note %}&asymp;{% endif %} </td>
	            <td style="text-align:center;">{% ifnotequal task.comment_set.all.count 0  %}{{ task.comment_set.all.count }}{% endifnotequal %}

	            </td>
	            {% ifequal list_slug "mine" %}
                <td><a href="{% url todo-incomplete_tasks task.list.id task.list.slug %}">{{ task.list }}</a></td>
                {% endifequal %}

	            <td><input type="checkbox" name="del_task" value="{{ task.id }}" id="del_task_{{ task.id }}">   </td>
            </tr>
	    {% endfor %}
	</table>
    <p><input type="submit" name="mark_tasks_done" value="Continue..."  class="todo-button"></p>

    <p><a  class="todo" href="{% url todo-completed_tasks list_id list_slug %}">View completed tasks</a></p>
    {% endifequal %}

    {% ifequal view_completed 1 %}
	<h3>Completed tasks</h3>

	<table border="0"  id="tasktable">
        <tr>
            <th>Undo</th>
            <th>Task</th>
            <th>Created</th>
            <th>Completed on</th>
            <th>Note</th>
            <th>Comm</th>
            {% ifequal list_slug "mine" %}
            <th>List</th>
             {% endifequal %}
            <th>Del</th>
        </tr>


		{% for task in completed_list %}
	        <tr class="{% cycle 'row1' 'row2' %}">
	            <td><input type="checkbox" name="undo_completed_task" value="{{ task.id }}" id="id_undo_completed_task{{ task.id }}">   </td>
	            <td><a href="{% url todo-task_detail task.id %}">{{ task.title|truncatewords:20 }}</a></td>
	            <td>{{ task.created_date|date:"m/d/Y" }}</td>
	            <td>{{ task.completed_date|date:"m/d/Y" }}</td>
	            <td style="text-align:center;">{% if task.note %}&asymp;{% endif %} </td>
	            <td style="text-align:center;">{% ifnotequal task.comment_set.all.count 0  %}{{ task.comment_set.all.count }}{% endifnotequal %}

	            <td><input type="checkbox" name="del_completed_task" value="{{ task.id }}" id="del_completed_task_{{ task.id }}">   </td>
            </tr>
	    {% endfor %}

	</table>
	<p><input type="submit" name="deldonetasks" value="Continue..."  class="todo-button"></p>
	</form>
    <p><a  class="todo" href="{% url todo-incomplete_tasks list_id list_slug %}">View incomplete tasks</a></p>
    {% endifequal %}

	{% ifequal can_del 1 %}
	{% ifnotequal list_slug "mine" %}
	   <p><a class="todo" href="{% url todo-del_list list_id list_slug %}">Delete this list</a></p>
	{% endifnotequal %}
	{% endifequal %}

    {% endifequal %}
{% endblock %}

todo/templates/todo/view_task.html
{% extends "todo/base.html" %}

{% block title %}Task: {{ task.title }}{% endblock %}

{% block body %}

<script type="text/javascript">

$(document).ready(function() {
    // Initially hide the TaskEdit form
    $('#TaskEdit').hide();

    // toggle slide to show the Add Task form when link clicked
    $('#slideToggle').click(function(){
        $(this).siblings('#TaskEdit').slideToggle();
    });
});
</script>


{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}



{% ifequal auth_ok 1 %}

<h2>{{ task }}</h2>


<form action="" method="POST">
<p style="margin-bottom:0px;" id="slideToggle" >&rarr; Click to edit details &larr;</p>

<p><strong>In list:</strong> <a href="{% url todo-incomplete_tasks task.list.id task.list.slug %}" class="showlink">{{ task.list }}</a><br /></p>

<p>
<strong>Assigned to:</strong> {{ task.assigned_to.first_name }} {{ task.assigned_to.last_name }}<br />
<strong>Due date:</strong>  {{ task.due_date }}<br />
<strong>Completed:</strong> {{ form.completed }}<br />
</p>


{% if task.note %}
<p><strong>Note:</strong> {{ task.note|safe|linebreaks }}</p>
{% endif %}

<div id="TaskEdit">
<h3>Edit Task</h3>

<table>
    {{ form.management_form }}


    {{ form.id }}
<tr>
    <td>Task:</td>
    <td>{{ form.title }}  </td>
</tr>



<tr>
    <td>Created:</td>
    <td>{{ form.created_date }}  </td>
</tr>

<tr>
    <td>Due:</td>
    <td>{{ form.due_date }}  </td>
</tr>





<tr>
    <td>Assigned to:</td>
    <td>{{ form.assigned_to }}  </td>
</tr>

<tr>
    <td valign="top">Note:</td>
    <td>{{ form.note }}  </td>
</tr>

<tr>
    <td>Priority:</td>
    <td>{{ form.priority }}  </td>
</tr>

</table>
<p><input type="submit" class="todo-button" name="edit_task" value="Edit task"></p>
</div>


<hr />


<h3>Add comment</h3>

    <textarea name="comment-body" rows="8" cols="40"></textarea>
    <p><input class="todo-button"type="submit" value="Submit"></p>

</form>

<h3>Comments on this task</h3>

{% for comment in comment_list %}
    <p><strong>{{ comment.author.first_name }} {{ comment.author.last_name }}, {{ comment.date|date:"F d Y" }}</strong> </p>
    {{ comment.body|safe|linebreaks }}
{% endfor %}



{% endifequal %}

{% endblock %}